-- MySQL Script generated by MySQL Workbench
-- Mon Jul 12 16:48:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `codcategoria` INT NOT NULL,
  `categoria` VARCHAR(70) NULL,
  PRIMARY KEY (`codcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `codcidade` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  PRIMARY KEY (`codcidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `codfornecedor` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `num` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `contrato` VARCHAR(45) NULL,
  `cnpj` INT NULL,
  `insc` VARCHAR(45) NULL,
  `tel` BIGINT(10) NULL,
  `Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codfornecedor`, `Cidade_codcidade`),
  INDEX `fk_Fornecedor_Cidade1_idx` (`Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_Fornecedor_Cidade1`
    FOREIGN KEY (`Cidade_codcidade`)
    REFERENCES `mydb`.`Cidade` (`codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codproduto` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `peso` DOUBLE NULL,
  `controlado` VARCHAR(45) NULL,
  `qtdemin` DOUBLE NULL,
  `Categoria_codcategoria` INT NOT NULL,
  `Fornecedor_codfornecedor` INT NOT NULL,
  PRIMARY KEY (`codproduto`, `Categoria_codcategoria`, `Fornecedor_codfornecedor`),
  INDEX `fk_Produto_Categoria_idx` (`Categoria_codcategoria` ASC) ,
  INDEX `fk_Produto_Fornecedor1_idx` (`Fornecedor_codfornecedor` ASC) ,
  CONSTRAINT `fk_Produto_Categoria`
    FOREIGN KEY (`Categoria_codcategoria`)
    REFERENCES `mydb`.`Categoria` (`codcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_codfornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`codfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trasnportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trasnportadora` (
  `codtransportadora` INT NOT NULL,
  `transportadora` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `num` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` INT NULL,
  `cnpj` INT NULL,
  `insc` INT NULL,
  `tel` BIGINT(10) NULL,
  `trasnportadoracol` VARCHAR(45) NULL,
  `trasnportadoracol1` VARCHAR(45) NULL,
  `Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codtransportadora`, `Cidade_codcidade`),
  INDEX `fk_trasnportadora_Cidade1_idx` (`Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_trasnportadora_Cidade1`
    FOREIGN KEY (`Cidade_codcidade`)
    REFERENCES `mydb`.`Cidade` (`codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrada` (
  `codentrada` INT NOT NULL,
  `dataped` DATE NULL,
  `dataentr` DATE NULL,
  `total` VARCHAR(45) NULL,
  `frete` DOUBLE NULL,
  `numnf` INT NULL,
  `imposto` VARCHAR(45) NULL,
  `trasnportadora_codtransportadora` INT NOT NULL,
  `trasnportadora_Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codentrada`, `trasnportadora_codtransportadora`, `trasnportadora_Cidade_codcidade`),
  INDEX `fk_Entrada_trasnportadora1_idx` (`trasnportadora_codtransportadora` ASC, `trasnportadora_Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_Entrada_trasnportadora1`
    FOREIGN KEY (`trasnportadora_codtransportadora` , `trasnportadora_Cidade_codcidade`)
    REFERENCES `mydb`.`trasnportadora` (`codtransportadora` , `Cidade_codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemEntrada` (
  `codeitementrada` INT NOT NULL,
  `lote` VARCHAR(45) NULL,
  `qtde` INT NULL,
  `valor` FLOAT NULL,
  `Produto_codproduto` INT NOT NULL,
  `Produto_Categoria_codcategoria` INT NOT NULL,
  `Entrada_codentrada` INT NOT NULL,
  `Entrada_trasnportadora_codtransportadora` INT NOT NULL,
  `Entrada_trasnportadora_Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codeitementrada`, `Produto_codproduto`, `Produto_Categoria_codcategoria`, `Entrada_codentrada`, `Entrada_trasnportadora_codtransportadora`, `Entrada_trasnportadora_Cidade_codcidade`),
  INDEX `fk_ItemEntrada_Produto1_idx` (`Produto_codproduto` ASC, `Produto_Categoria_codcategoria` ASC) ,
  INDEX `fk_ItemEntrada_Entrada1_idx` (`Entrada_codentrada` ASC, `Entrada_trasnportadora_codtransportadora` ASC, `Entrada_trasnportadora_Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_ItemEntrada_Produto1`
    FOREIGN KEY (`Produto_codproduto` , `Produto_Categoria_codcategoria`)
    REFERENCES `mydb`.`Produto` (`codproduto` , `Categoria_codcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemEntrada_Entrada1`
    FOREIGN KEY (`Entrada_codentrada` , `Entrada_trasnportadora_codtransportadora` , `Entrada_trasnportadora_Cidade_codcidade`)
    REFERENCES `mydb`.`Entrada` (`codentrada` , `trasnportadora_codtransportadora` , `trasnportadora_Cidade_codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja` (
  `codloja` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `num` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `tel` BIGINT(10) NULL,
  `insc` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codloja`, `Cidade_codcidade`),
  INDEX `fk_Loja_Cidade1_idx` (`Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_Loja_Cidade1`
    FOREIGN KEY (`Cidade_codcidade`)
    REFERENCES `mydb`.`Cidade` (`codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saida` (
  `codsaida` INT NOT NULL,
  `total` VARCHAR(45) NULL,
  `frete` DOUBLE NULL,
  `imposto` VARCHAR(45) NULL,
  `Loja_codloja` INT NOT NULL,
  `Loja_Cidade_codcidade` INT NOT NULL,
  `trasnportadora_codtransportadora` INT NOT NULL,
  `trasnportadora_Cidade_codcidade` INT NOT NULL,
  PRIMARY KEY (`codsaida`, `Loja_codloja`, `Loja_Cidade_codcidade`, `trasnportadora_codtransportadora`, `trasnportadora_Cidade_codcidade`),
  INDEX `fk_Saida_Loja1_idx` (`Loja_codloja` ASC, `Loja_Cidade_codcidade` ASC) ,
  INDEX `fk_Saida_trasnportadora1_idx` (`trasnportadora_codtransportadora` ASC, `trasnportadora_Cidade_codcidade` ASC) ,
  CONSTRAINT `fk_Saida_Loja1`
    FOREIGN KEY (`Loja_codloja` , `Loja_Cidade_codcidade`)
    REFERENCES `mydb`.`Loja` (`codloja` , `Cidade_codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saida_trasnportadora1`
    FOREIGN KEY (`trasnportadora_codtransportadora` , `trasnportadora_Cidade_codcidade`)
    REFERENCES `mydb`.`trasnportadora` (`codtransportadora` , `Cidade_codcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemSaida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemSaida` (
  `coditementrada` INT NOT NULL,
  `lote` VARCHAR(45) NULL,
  `qtde` INT NULL,
  `valor` DOUBLE NULL,
  `ItemSaidacol` VARCHAR(45) NULL,
  `Produto_codproduto` INT NOT NULL,
  `Produto_Categoria_codcategoria` INT NOT NULL,
  `Produto_Fornecedor_codfornecedor` INT NOT NULL,
  `Saida_codsaida` INT NOT NULL,
  PRIMARY KEY (`coditementrada`, `Produto_codproduto`, `Produto_Categoria_codcategoria`, `Produto_Fornecedor_codfornecedor`, `Saida_codsaida`),
  INDEX `fk_ItemSaida_Produto1_idx` (`Produto_codproduto` ASC, `Produto_Categoria_codcategoria` ASC, `Produto_Fornecedor_codfornecedor` ASC) ,
  INDEX `fk_ItemSaida_Saida1_idx` (`Saida_codsaida` ASC) ,
  CONSTRAINT `fk_ItemSaida_Produto1`
    FOREIGN KEY (`Produto_codproduto` , `Produto_Categoria_codcategoria` , `Produto_Fornecedor_codfornecedor`)
    REFERENCES `mydb`.`Produto` (`codproduto` , `Categoria_codcategoria` , `Fornecedor_codfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemSaida_Saida1`
    FOREIGN KEY (`Saida_codsaida`)
    REFERENCES `mydb`.`Saida` (`codsaida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into Categoria values ('joao', 'm', 'joao@gmail.com', 988638273, '22923110', ' maia lacerda - estacio - rio - rj'),
						('lilian','f', 'senador soares tijuca - rio - rj','947785696'87774856);
